# dev configuration
dynamoDB:
  stackName: 'BeerpongoDynamoDbStackDev'
  gamesTable:
    id: 'BeerpongoDevGamesTable'
    tableName: 'BeerpongoDevGamesTable'

APIGateway:
  stackName: 'BeerpongoAPIGatewayStackDev'
  apiFile: './config/api_beerpongo.json'
  id: 'Beerpongo-api'